### ISSUE TITLE
Multiple malformed URIs

### ISSUE THREAD

**Issue by dillerm** [yuki-yamagata/hoip#1]
I was just looking at your ontology in BioPortal and noticed that a few imported classes seem to have malformed URIs.

Two seem to have concatenated the source ontology's URI with HOIP's URI:

- http://purl.bioontology.org/ontology/HOIP/http://purl.obolibrary.org/obo/CHEBI_50803
- http://purl.bioontology.org/ontology/HOIP/http://purl.obolibrary.org/obo/GO_0030193

There are also several that assign a HOIP base URI to imported classes (this list may not be exhaustive):

- http://purl.bioontology.org/ontology/HOIP/GO_0019061
- http://purl.bioontology.org/ontology/HOIP/GO_0019080
- http://purl.bioontology.org/ontology/HOIP/GO_0039690
- http://purl.bioontology.org/ontology/HOIP/GO_0046718

**Comment by yuki-yamagata** [comment]
> Two seem to have concatenated the source ontology's URI with HOIP's URI:
> * http://purl.bioontology.org/ontology/HOIP/http://purl.obolibrary.org/obo/CHEBI_50803
> * http://purl.bioontology.org/ontology/HOIP/http://purl.obolibrary.org/obo/GO_0030193

Thank you for checking. 
I'll fix and update it.

> There are also several that assign a HOIP base URI to imported classes (this list may not be exhaustive):
> * http://purl.bioontology.org/ontology/HOIP/GO_0019061
> * http://purl.bioontology.org/ontology/HOIP/GO_0019080
> * http://purl.bioontology.org/ontology/HOIP/GO_0039690
> * http://purl.bioontology.org/ontology/HOIP/GO_0046718

Sorry, these are test terms. I forgot deleting in public. So, I'll delete them.
In the HoIP ontology, many entities are specialized in GO terms.
For example, 
uncoating of virus (GO:0019061)
 uncoating of virus in COVID-19 (HOIP_0037062) ＊
I want to distinguish GO-derived specialized terms or HoIP-specific terms ( like abnormal related terms, which are not in GO), so I tested the URI using the GOID. 
However, it might be misleading, and I didn't proceed with this idea.

Thanks,

**Comment by dillerm** [comment]
Sounds good! I figured I'd bring it to your attention just in case you had missed it.

**Comment by yuki-yamagata** [comment]
I updated.
I really appreciate your support😃
